### ISSUE TITLE
Experience Bar

### ISSUE THREAD

**Issue by Extarys** [Sirillion/SMXhud#3]
It would be nice to have the experience bar above the belt or something to see our current experience and needed experience like the vanilla HUD.

**Comment by Sirillion** [comment]
There is an experience bar in SMXhud, it is in the top left corner surrounding the level display. Next to the clock :)

**Comment by Extarys** [comment]
Can't believe I never noticed that, I'm sorry!
And it looks great too! I feel so dump :laughing: 
Thanks for your hard work - keep it up!
