### ISSUE TITLE
Ammunition and other stats not showing in bottom right corner

### ISSUE THREAD

**Issue by schallinterferenz** [Sirillion/SMXhud#5]
Hello, 

The Ammunition Item in the bottom right corner is not showing anything. I tried editing it by commenting out the sprite but it didn't help.

Any suggestions on this problem? 

Greets

**Comment by schallinterferenz** [comment]
![20230818225700_1](https://github.com/Sirillion/SMXhud/assets/36766538/05d7a33c-f4e3-4ae7-a8c3-6ba8d356eaba)
![20230818225431_1](https://github.com/Sirillion/SMXhud/assets/36766538/53a32bad-48cd-4801-af60-c4a170f9f8bb)

**Comment by Sirillion** [comment]
You haven't updated to the latest version. Due to work it is currently only updated on Nexusmods.

**Comment by schallinterferenz** [comment]
It worked after downloading and installing version from Nexus Mods! Thank you very much :)
